name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define the version to be published (SemVer)'
        required: true
        type: string
      package:
        description: 'Select which package to stage for publish'
        required: true
        default: 'warning'
        type: choice
        options:
        - FluentSerializer.Core
        - FluentSerializer.Core.DependencyInjection.NetCoreDefault
        - FluentSerializer.Json
        - FluentSerializer.Json.DependencyInjection.NetCoreDefault
        - FluentSerializer.Xml
        - FluentSerializer.Xml.DependencyInjection.NetCoreDefault

jobs:
  dotnet-push:
    name: "Push to NuGet.org"

    runs-on: ubuntu-latest

    environment:
      name: NuGet
      url: "https://www.nuget.org/packages/${{ github.event.inputs.package }}/${{ github.event.inputs.version }}"

    steps:
    ###
    # Checkout repository
    ###
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true
    ###
    # 🧰 Setup .Net
    #
    # Configure the pipeline to use the correct .Net sdk versions
    ###
    - name: 🧰 Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        include-prerelease: true
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
    ###
    # 🔧 Fix version
    #
    # Override the libraries version info
    ###
    - name: 🔧 Fix version
      shell: pwsh
      run: |-
        ${{github.workspace}}/.github/workflows/update-version.ps1 `
          -Version "${{ github.event.inputs.version }}" `
          -File "${{github.workspace}}/src/${{ github.event.inputs.package }}/${{ github.event.inputs.package }}.csproj";
    ###
    # 🗃 Restore dependencies
    #
    # Fill the NuGet store with necessary libraries
    ###
    - name: 🗃 Restore dependencies
      run: dotnet restore
    ###
    # 🛠 Build
    #
    # Build the library code for later use
    ###
    - name: 🛠 Build
      run: dotnet build --no-restore --nologo --configuration "Release" -p:Version=${{ github.event.inputs.version }}
    ###
    # 🗳 Push package
    #
    # Pack and push the package
    ###
    - name: 🗳 Push package
      run: >#!
        sudo dotnet nuget push ${{github.workspace}}/src/${{ github.event.inputs.package }}/bin/release/${{ github.event.inputs.version }}.${{ github.event.inputs.package }}.nupkg
        --api-key ${{ secrets.NUGET_TOKEN }}
        --source https://api.nuget.org/v3/index.json
      working-directory: ${{github.workspace}}/src/${{ github.event.inputs.package }}