name: "Continuous integration - Run Stryker"
on:
  workflow_call:
    secrets:
      STRYKER_DASHBOARD_API_KEY:
        required: true

permissions:
  contents: read

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
  TERM: xterm-color
  DOTNET_SDK_VERSION: "9.0.x"

jobs:
  stryker:
    strategy:
      fail-fast: false
      matrix:
        libraryName: [ "Core", "Xml", "Json" ]
    name: "${{ matrix.libraryName }}"
    runs-on: ubuntu-latest
    steps:
    ###
    # Checkout repository
    ###
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    ###
    # 🧰 Install .Net SDK
    #
    # Configure the pipeline to use the correct .Net sdk version
    ###
    - name: 🧰 Install .Net SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    ###
    # 🧰 Setup .Net tools
    #
    # Register tools necessary to run the `test` pipeline-job
    ###
    - name: 🧰 Setup .NET tools
      run: |-
        dotnet tool install --global dotnet-stryker
      # ln -s /usr/lib/libssl.so.47.0.6 /usr/lib/libssl.so.1.0.0
    ###
    # 🛠 Build & Run
    #
    # Run Stryker.Net over codebase
    # debug verbosity because we don't have the progress reporter in pipelines
    #
    # Note: The dotnet build before stryker is necessary for net7
    # Hopefully, this is a temporary fix
    #
    # The additional echo is because the stryker report URL get's weird line cutoff.
    ###
    - name: 🛠 Build & Run
      run: >-
        echo "https://dashboard.stryker-mutator.io/reports/github.com/Marvin-Brouwer/FluentSerializer/${{ github.ref }}";

        dotnet stryker
        --config-file "stryker-config.pipeline.json"
        --version "${{ github.ref }}"
        --mutation-level "Complete"
        --break-at 75
        --threshold-low 80
        --dashboard-api-key "${{ secrets.STRYKER_DASHBOARD_API_KEY }}"

        echo "::remove-matcher owner=csc::"

        echo "::remove-matcher owner=dotnet::"
      working-directory: ${{github.workspace}}/src/FluentSerializer.${{ matrix.libraryName }}