name: "Continuous integration - Stryker"
on:
  workflow_call:
    secrets:
      STRYKER_DASHBOARD_API_KEY:
        required: true

env:
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

jobs:
  stryker-core:
    name: "Mutate"
    strategy:
      fail-fast: true
      matrix:
        libraryName: [ "Core", "Xml", "Json" ]
    uses: ./.github/workflows/continuous-integration.run-stryker.yml
    secrets: inherit
    with:
      libraryName: ${{ matrix.libraryName }}